//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yummy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
        public int MealId { get; set; }
        public int CuisineId { get; set; }
    
        public virtual Cuisine Cuisine { get; set; }
        public virtual MealType MealType { get; set; }
    }
}
